import { generatedArt } from './generated-art';
import { animalArt, type AnimalKind } from './animal-art';

export type EngravingCategory = 'animals' | 'botanical' | 'specimens' | 'anatomy' | 'instruments' | 'celestial' | 'architecture' | 'machines' | 'ornaments' | 'technology' | 'ai' | 'money';
type Engraving = { label: string; file: string; width: number; height: number; year: string; source: string; category: EngravingCategory };

/** Unmodified archive images. Source records and rights are in docs/graphics-sources.md. */
const additionalEngravings = {
  "male-fern-1913": {"label": "Male Fern", "file": "/engravings/male-fern-1913.png", "width": 500, "height": 694, "year": "1913", "source": "https://commons.wikimedia.org/wiki/File:BB-0045_Dryopteris_filix-mas.png", "category": "botanical"},
  "cultivated-mushrooms-1904": {"label": "Cultivated Mushrooms", "file": "/engravings/cultivated-mushrooms-1904.png", "width": 2800, "height": 3307, "year": "1904", "source": "https://commons.wikimedia.org/wiki/File:Champignon_de_couche_Vilmorin-Andrieux_1904.png", "category": "botanical"},
  "dandelion-1913": {"label": "Red-seeded Dandelion", "file": "/engravings/dandelion-1913.jpg", "width": 600, "height": 789, "year": "1913", "source": "https://commons.wikimedia.org/wiki/File:Taraxacum_erythrospermum-usda-1.jpg", "category": "botanical"},
  "vosges-carrot-1904": {"label": "Vosges Carrot", "file": "/engravings/vosges-carrot-1904.png", "width": 2328, "height": 3124, "year": "1904", "source": "https://commons.wikimedia.org/wiki/File:Carotte_blanche_des_Vosges_Vilmorin-Andrieux_1904.png", "category": "botanical"},
  "swallowtail-butterfly-1911": {"label": "Swallowtail Butterfly", "file": "/engravings/swallowtail-butterfly-1911.jpg", "width": 500, "height": 444, "year": "1911", "source": "https://commons.wikimedia.org/wiki/File:EB1911_Lepidoptera_-_Papilio_machaon.jpg", "category": "specimens"},
  "tiger-beetle-1911": {"label": "Tiger Beetle", "file": "/engravings/tiger-beetle-1911.png", "width": 500, "height": 625, "year": "1911", "source": "https://commons.wikimedia.org/wiki/File:EB_1911_Manticora_tuberculata.png", "category": "specimens"},
  "resting-dragonfly-1911": {"label": "Resting Dragonfly", "file": "/engravings/resting-dragonfly-1911.jpg", "width": 330, "height": 451, "year": "1911", "source": "https://commons.wikimedia.org/wiki/File:Britannica_Dragon-fly_4.jpg", "category": "specimens"},
  "murex-shell-1896": {"label": "Murex Shell", "file": "/engravings/murex-shell-1896.jpg", "width": 960, "height": 594, "year": "1896", "source": "https://commons.wikimedia.org/wiki/File:PSM_V50_D067_Murex_ramosus.jpg", "category": "specimens"},
  "anatomy-skull-britannica": {"label": "Human Skull", "file": "/engravings/anatomy-skull-britannica.jpg", "width": 500, "height": 526, "year": "1911", "source": "https://commons.wikimedia.org/wiki/File:EB1911_Skull_-_norma_lateralis.jpg", "category": "anatomy"},
  "anatomy-hand-foot": {"label": "Hand & Foot Skeletons", "file": "/engravings/anatomy-hand-foot.png", "width": 330, "height": 481, "year": "1897–1898 (volume publication)", "source": "https://commons.wikimedia.org/wiki/File:PSM_V52_D544_Human_hands_and_feet.png", "category": "anatomy"},
  "anatomy-optic-nerve": {"label": "Eye & Optic Nerve", "file": "/engravings/anatomy-optic-nerve.png", "width": 500, "height": 310, "year": "1918 edition", "source": "https://commons.wikimedia.org/wiki/File:Gray880.png", "category": "anatomy"},
  "anatomy-heart-section": {"label": "Human Heart", "file": "/engravings/anatomy-heart-section.png", "width": 475, "height": 416, "year": "1918 edition", "source": "https://commons.wikimedia.org/wiki/File:Gray_internal_structure_of_heart.png", "category": "anatomy"},
  "instruments-hooke-microscope": {"label": "Hooke Microscope", "file": "/engravings/instruments-hooke-microscope.png", "width": 625, "height": 693, "year": "1665", "source": "https://commons.wikimedia.org/wiki/File:Hooke-microscope.png", "category": "instruments"},
  "instruments-buckingham-telescope": {"label": "Buckingham Telescope", "file": "/engravings/instruments-buckingham-telescope.jpg", "width": 500, "height": 587, "year": "1869", "source": "https://commons.wikimedia.org/wiki/File:Buckingham_telescope_-_Im1869EnV27-p005.jpg", "category": "instruments"},
  "instruments-chaucer-astrolabe": {"label": "Chaucer Astrolabe", "file": "/engravings/instruments-chaucer-astrolabe.jpg", "width": 500, "height": 499, "year": "1852", "source": "https://commons.wikimedia.org/wiki/File:Chaucer_astrolabe_1.jpg", "category": "instruments"},
  "instruments-travelers-sundial": {"label": "Traveler’s Sundial", "file": "/engravings/instruments-travelers-sundial.png", "width": 960, "height": 979, "year": "1891", "source": "https://commons.wikimedia.org/wiki/File:Traveler%27s_sundial_-_Project_Gutenberg_eText_15050.png", "category": "instruments"},
  "celestial-mellan-moon": {"label": "Full Moon", "file": "/engravings/celestial-mellan-moon.jpg", "width": 960, "height": 1090, "year": "1635", "source": "https://commons.wikimedia.org/wiki/File:Full_moon_by_Claude_Mellan_1635.jpg", "category": "celestial"},
  "celestial-kircher-sun": {"label": "Kircher’s Sun", "file": "/engravings/celestial-kircher-sun.jpg", "width": 960, "height": 855, "year": "1664", "source": "https://commons.wikimedia.org/wiki/File:Kircher_Mundus_Subterraneus_illustration_of_the_Sun.jpg", "category": "celestial"},
  "celestial-six-tailed-comet": {"label": "Six-Tailed Comet", "file": "/engravings/celestial-six-tailed-comet.jpg", "width": 960, "height": 981, "year": "19th century; depicts the comet of 1744", "source": "https://commons.wikimedia.org/wiki/File:Comet_with_six_tails.jpg", "category": "celestial"},
  "celestial-orion-hevelius": {"label": "Orion", "file": "/engravings/celestial-orion-hevelius.jpg", "width": 960, "height": 796, "year": "1690", "source": "https://commons.wikimedia.org/wiki/File:Orion_constellation_Hevelius.jpg", "category": "celestial"},
  "architecture-column": {"label": "Carcassonne column", "file": "/engravings/architecture-column.png", "width": 1280, "height": 3559, "year": "1856", "source": "https://commons.wikimedia.org/wiki/File:Colonne.cathedrale.Carcassonne.png", "category": "architecture"},
  "architecture-capital": {"label": "Sainte-Chapelle capital", "file": "/engravings/architecture-capital.png", "width": 696, "height": 897, "year": "1856", "source": "https://commons.wikimedia.org/wiki/File:Chapiteau.arcature.Sainte.Chapelle.Paris.png", "category": "architecture"},
  "architecture-finial": {"label": "Chartres carved finial", "file": "/engravings/architecture-finial.png", "width": 1280, "height": 2286, "year": "1856", "source": "https://commons.wikimedia.org/wiki/File:Fleuron.cathedrale.Chartres.png", "category": "architecture"},
  "architecture-flying-buttress": {"label": "Sainte-Chapelle flying buttress", "file": "/engravings/architecture-flying-buttress.png", "width": 1280, "height": 1667, "year": "1856", "source": "https://commons.wikimedia.org/wiki/File:Arc.boutant.Sainte.Chapelle.Paris.png", "category": "architecture"},
  "machine-clockwork": {"label": "Clock chime mechanism", "file": "/engravings/machine-clockwork.jpg", "width": 1280, "height": 1431, "year": "1886", "source": "https://commons.wikimedia.org/wiki/File:PSM_V29_D201_Clock_mechanism_for_hourly_chime.jpg", "category": "machines"},
  "machine-steam-engine": {"label": "Steam household motor", "file": "/engravings/machine-steam-engine.jpg", "width": 1280, "height": 2711, "year": "1880–1881", "source": "https://commons.wikimedia.org/wiki/File:PSM_V18_D340_Steam_driven_household_motor.jpg", "category": "machines"},
  "machine-worm-gears": {"label": "Worm gear", "file": "/engravings/machine-worm-gears.png", "width": 1280, "height": 894, "year": "1908", "source": "https://commons.wikimedia.org/wiki/File:Chambers_1908_Endless_Screw.png", "category": "machines"},
  "machine-flying-machine": {"label": "Du Temple flying machine", "file": "/engravings/machine-flying-machine.png", "width": 1280, "height": 715, "year": "1857", "source": "https://commons.wikimedia.org/wiki/File:1857_patent_drawing_of_Du_Temple_monoplane.png", "category": "machines"},
  "ornament-initial-r": {"label": "Floral initial R", "file": "/engravings/ornament-initial-r.jpg", "width": 2952, "height": 2931, "year": "1496", "source": "https://commons.wikimedia.org/wiki/File:Initial_letter_R_with_floral_pattern_MET_DP855225.jpg", "category": "ornaments"},
  "ornament-flourish": {"label": "Leaf flourish", "file": "/engravings/ornament-flourish.png", "width": 960, "height": 563, "year": "1909", "source": "https://commons.wikimedia.org/wiki/File:Ornament_1,_Clouds_without_Water_(Crowley,_1909).png", "category": "ornaments"},
  "ornament-flowers": {"label": "Printer flowers", "file": "/engravings/ornament-flowers.jpg", "width": 1280, "height": 251, "year": "1911", "source": "https://commons.wikimedia.org/wiki/File:Ornement_typographique,_quatre_bouquets_de_fleurs.jpg", "category": "ornaments"},
  "ornament-divider": {"label": "Floral divider", "file": "/engravings/ornament-divider.jpg", "width": 960, "height": 214, "year": "1886", "source": "https://commons.wikimedia.org/wiki/File:Endpiece_from_Three_Stories_(2)_rotated.jpg", "category": "ornaments"},
} as const satisfies Record<string, Engraving>;
const animals = Object.fromEntries(Object.entries(animalArt).map(([kind, art]) => [kind, { ...art, category: 'animals' as const }])) as { [K in AnimalKind]: (typeof animalArt)[K] & { category: 'animals' } };
export const engravingArt = { ...animals, ...additionalEngravings, ...generatedArt };
export type EngravingKind = keyof typeof engravingArt;
export function isEngraving(kind: string): kind is EngravingKind { return Object.hasOwn(engravingArt, kind); }
